### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by Tobypoodle** [neilenns/ambientweather2mqtt#106]
Using version 4.0.3

From logs, and repeats everytime weather station updates

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at processWeatherData (/home/node/app/dist/controllers/weatherDataController.js:119:146)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:346:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/node/app/node_modules/express/lib/middleware/init.js:40:5)

**Comment by neilenns** [comment]
Interesting. Can you turn on verbose logging in the add-on options, then look at the log and paste in all the text after it has received an update from the station? Thanks!

**Comment by Tobypoodle** [comment]
2023-05-25T12:53:54-05:00 [Main] Starting up
2023-05-25T12:53:54-05:00 [MQTT] Connected to MQTT server http://192.168.86.68:1883
2023-05-25T12:53:54-05:00 [Web server] Listening at http://localhost:8132
2023-05-25T12:53:54-05:00 [Weather handler] /data/?ID=bradstation&PASSWORD=fakestationkey&tempf=84.38&humidity=57&dewptf=67.46&windchillf=84.38&winddir=345&windspeedmph=0.00&windgustmph=2.46&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.354&monthlyrainin=3.248&yearlyrainin=11.701&solarradiation=718.94&UV=6&indoortempf=81.86&indoorhumidity=44&baromin=29.873&temp3f=99.14&humidity3=43&soilmoisture=38&lowbatt=0&dateutc=now&softwaretype=OBSERVERIP2_V2.2.3&action=updateraw&realtime=1&rtfreq=5
2023-05-25T12:53:54-05:00 [Weather handler] {
  "ID": "bradstation",
  "PASSWORD": "fakestationkey",
  "tempf": "84.38",
  "humidity": "57",
  "dewptf": "67.46",
  "windchillf": "84.38",
  "winddir": "345",
  "windspeedmph": "0.00",
  "windgustmph": "2.46",
  "rainin": "0.000",
  "dailyrainin": "0.000",
  "weeklyrainin": "0.354",
  "monthlyrainin": "3.248",
  "yearlyrainin": "11.701",
  "solarradiation": "718.94",
  "UV": "6",
  "indoortempf": "81.86",
  "indoorhumidity": "44",
  "baromin": "29.873",
  "temp3f": "99.14",
  "humidity3": "43",
  "soilmoisture": "38",
  "lowbatt": "0",
  "dateutc": "now",
  "softwaretype": "OBSERVERIP2_V2.2.3",
  "action": "updateraw",
  "realtime": "1",
  "rtfreq": "5"
}
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at processWeatherData (/home/node/app/dist/controllers/weatherDataController.js:119:146)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/node/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/node/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:346:12)
    at next (/home/node/app/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/node/app/node_modules/express/lib/middleware/init.js:40:5)

**Comment by neilenns** [comment]
This looks like a bug in your weather station. Which one is it? It is sending the following value for the date:

`dateutc=now`

That's definitely not a date 😂

**Comment by Tobypoodle** [comment]
makes sense.  Let me get a thread with them going.  Appreciate quick response and pointed in right direction.

**Comment by neilenns** [comment]
@Tobypoodle This should be fixed with 4.0.4.

You can force Home Assistant to check for the update by going to the Add-On Store, selecting `...` in the top right, then `Check for updates`.

**Comment by Tobypoodle** [comment]
and now I see the data coming through to HA.   Outstanding, thank you.  BTW, I did open a ticket w/ ambient,  they seemed to understand the issue and dev team is looking into it.   take care.  -brad

**Comment by neilenns** [comment]
Nice!
