### ISSUE TITLE
Exception with HA 2023.5.2

### ISSUE THREAD

**Issue by drjjr2** [neilenns/ambientweather2mqtt#99]
Getting the following error after updating to 2023.5.2:

```
2023-05-08 13:30:30.796 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.eventdate, topic: 'homeassistant/sensor/BCFF4D81C70A/eventDate/state' with payload: b'Mon, 08 May 2023 18:30:30 GMT'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'Mon, 08 May 2023 18:30:30 GMT'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.eventdate has device class None, state class measurement unit timestamp and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: Mon, 08 May 2023 18:30:30 GMT (<class 'str'>)
```

**Comment by neilenns** [comment]
Confirmed I see this on 2023.5.2 😒 Trying to figure out what they changed that broke this.

**Comment by neilenns** [comment]
I think it might be because of this change: https://github.com/home-assistant/core/pull/85605

**Comment by neilenns** [comment]
Found at least 5 other reports of add-ons hitting this. Nothing I can do at this point but wait for a new HA release that fixes it.

**Comment by neilenns** [comment]
Published this change, now I just have to figure out how to get HomeAssistant to recreate the sensor with the new type. I've nuked my old sensor but somehow the discovery message didn't get published on startup. Gotta mess around with this more tomorrow.

**Comment by neilenns** [comment]
Progress? Now I get this error:

> ValueError: Sensor sensor.eventdate has a unit of measurement and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp

So maybe I have to get rid of the unit of measurement and this will be solved.
